// AWS Backend Configuration
// Auto-generated by deploy.sh

const AWS_CONFIG = {
    // API Gateway endpoint
    API_ENDPOINT: 'https://fth8em7xy0.execute-api.ap-southeast-2.amazonaws.com/prod/',

    // Specific endpoints
    NOTE_GENERATION_ENDPOINT: 'note/generate',
    SUBSCRIPTION_CHECK_ENDPOINT: 'subscription/check',

    // AWS Region
    REGION: 'ap-southeast-2'
};

// Helper function to construct full URL
function getApiUrl(endpoint) {
    return `${AWS_CONFIG.API_ENDPOINT}${endpoint}`;
}

module.exports = {
    AWS_CONFIG,
    getApiUrl
};
